query ListPublicItems @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  somePublicItems {
    id
    name
    description
  }
}

query GetMyProfile @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  users(where: {uid: {eq_expr: "auth.uid"}}) {
    id
    username
    email
  }
}

mutation CreateMyItem($name: String!, $description: String!) @auth(level: USER) {
  items_insert(data: {
    name: $name,
    description: $description,
    ownerUid_expr: "auth.uid"
  })
}

mutation UpdateMyItem($id: ID!, $description: String!) @auth(level: USER) {
  items_update(
    key: {id: $id},
    data: {description: $description},
    where: {ownerUid: {eq_expr: "auth.uid"}}
  )
}